### ISSUE TITLE
redirects from www.veganwiki.info/XYZ should take XYZ as parameter

### ISSUE THREAD

**Issue by huggi** [guaka/veganwiki#16]
Hi, not sure if this is in conflict with the Cloudflare protection. http://www.veganwiki.info/Test ends up at: http://veganwiki.info/Main_Page which is a bit frustrating for users. Thanks for correction of the redirects :)

**Comment by huggi** [comment]
50% done :) 
1. I confirm that there is no error message
2. the parameter /xyz does not end up in a redirect to http://veganwiki.info/xyz

**Comment by guaka** [comment]
Fixed.
