### ISSUE TITLE
another sample (country template might be broken)

### ISSUE THREAD

**Issue by huggi** [guaka/veganwiki#17]
http://veganwiki.info/en/Canada

I added Vancouver and Victoria today (via Form and not manually).

http://veganwiki.info/en/Canada does not Show Vancouver or Victoria.

**Comment by guaka** [comment]
Ah Purge is the answer!
![screen shot 2015-09-09 at 12 25 15](https://cloud.githubusercontent.com/assets/54728/9759510/d9c33462-56ed-11e5-97e8-80c37fa88933.png)

**Comment by huggi** [comment]
haha, welcome back in 1984. can't you auto-purge all articles over night? Okay maybe than everything is screwed up the next morning, but I'm lazy like you :)

**Comment by guaka** [comment]
I think they will be purged automatically at some point, I'm not an expert
of MW or SMW cache though
