### ISSUE TITLE
German/Deutsch: veganwiki.info/de

### ISSUE THREAD

**Issue by guaka** [guaka/veganwiki#31]
Can be set up quickly.

Relation with http://de.veganwiki.org/?

**Comment by huggi** [comment]
Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 87 bytes) in /www/htdocs/v156463/de.veganwiki.org/inc/auth/plain.class.php on line 293

tryed to register myself.

**Comment by guaka** [comment]
http://veganwiki.info/de/ set up
