### ISSUE TITLE
Problem with VeganWiki template (adding additional restaurants in one place)

### ISSUE THREAD

**Issue by huggi** [guaka/veganwiki#4]
I've created for Singapore:
- http://veganwiki.info/en/Brownice
- http://veganwiki.info/en/Loving_Hut
- http://veganwiki.info/en/Veganburg

Result:
- http://veganwiki.info/en/Singapore
- Comment: There should be 3 places, I only see Brownice (it was the first I added)

**Comment by guaka** [comment]
Interesting, it's working fine on http://veganwiki.info/en/Berlin

**Comment by huggi** [comment]
Maybe it's because City/Country template is the same $namespace?
